apiVersion: apps/v1
kind: Deployment
metadata: 
  name: clientes
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: clientes
  template: 
    metadata: 
      labels: 
        app: clientes
    spec:
      containers:
      - name: clientes
        image: marcospffernandes/api-clientes
        resources: 
          limits: 
            memory: "128Mi"
            cpu: "250m"
        ports: 
          - containerPort: 5000
        envFrom:
          - configMapRef:
             name: api-configmap 