apiVersion: apps/v1
kind: Deployment
metadata: 
  name: inventario
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: inventario
  template: 
    metadata: 
      labels: 
        app: inventario
    spec:
      containers:
      - name: inventario
        image: marcospffernandes/api-inventario
        resources: 
          limits: 
            memory: "128Mi"
            cpu: "250m"
        ports: 
          - containerPort: 5002
        envFrom:
          - configMapRef:
             name: api-configmap